`timescale 1ns/1ps

// fir_filter.sv
// =============
// ECG Accelerator — 33-tap FIR lowpass filter
// Cutoff: 40 Hz at 360 Hz sample rate
// Architecture: direct form, Q1.15 arithmetic
// Direct 33-tap computation — no symmetry optimisation
//
// Interface:
//   clk        : system clock (100 MHz)
//   rst_n      : active-low synchronous reset
//   valid_in   : high for one cycle when sample_in is valid
//   sample_in  : Q1.15 signed ECG sample
//   valid_out  : high for one cycle when sample_out is valid
//   sample_out : Q1.15 signed filtered sample

module fir_filter (
    input  logic        clk,
    input  logic        rst_n,
    input  logic        valid_in,
    input  logic signed [15:0] sample_in,
    output logic        valid_out,
    output logic signed [15:0] sample_out
);

    // ─────────────────────────────────────────────────────────────
    // PARAMETERS
    // ─────────────────────────────────────────────────────────────
    localparam TAPS = 33;

    // ─────────────────────────────────────────────────────────────
    // FIR COEFFICIENTS — Q1.15 fixed point, all 33 values
    // Generated by Python: round(h * 32768) where h = firwin(33, 40/180)
    // Symmetric: coeffs_full[k] = coeffs_full[32-k]
    // ─────────────────────────────────────────────────────────────
    logic signed [15:0] coeffs_full [0:TAPS-1];

    initial begin
        coeffs_full[0]  = -16'd59;
        coeffs_full[1]  = -16'd62;
        coeffs_full[2]  = -16'd40;
        coeffs_full[3]  =  16'd29;
        coeffs_full[4]  =  16'd142;
        coeffs_full[5]  =  16'd240;
        coeffs_full[6]  =  16'd211;
        coeffs_full[7]  = -16'd41;
        coeffs_full[8]  = -16'd503;
        coeffs_full[9]  = -16'd983;
        coeffs_full[10] = -16'd1145;
        coeffs_full[11] = -16'd641;
        coeffs_full[12] =  16'd694;
        coeffs_full[13] =  16'd2699;
        coeffs_full[14] =  16'd4878;
        coeffs_full[15] =  16'd6568;
        coeffs_full[16] =  16'd7204;
        coeffs_full[17] =  16'd6568;
        coeffs_full[18] =  16'd4878;
        coeffs_full[19] =  16'd2699;
        coeffs_full[20] =  16'd694;
        coeffs_full[21] = -16'd641;
        coeffs_full[22] = -16'd1145;
        coeffs_full[23] = -16'd983;
        coeffs_full[24] = -16'd503;
        coeffs_full[25] = -16'd41;
        coeffs_full[26] =  16'd211;
        coeffs_full[27] =  16'd240;
        coeffs_full[28] =  16'd142;
        coeffs_full[29] =  16'd29;
        coeffs_full[30] = -16'd40;
        coeffs_full[31] = -16'd62;
        coeffs_full[32] = -16'd59;
    end

    // ─────────────────────────────────────────────────────────────
    // SHIFT REGISTER — stores last 33 samples
    // shift_reg[0] = most recent sample
    // shift_reg[32] = oldest sample
    // ─────────────────────────────────────────────────────────────
    logic signed [15:0] shift_reg [0:TAPS-1];

    // ─────────────────────────────────────────────────────────────
    // INTERMEDIATE SIGNALS — declared at module level
    // ─────────────────────────────────────────────────────────────
    logic signed [31:0] acc;
    logic signed [31:0] prod;
    integer k;

    // ─────────────────────────────────────────────────────────────
    // MAIN LOGIC
    // ─────────────────────────────────────────────────────────────
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            for (k = 0; k < TAPS; k++)
                shift_reg[k] <= 16'sd0;
            valid_out  <= 1'b0;
            sample_out <= 16'sd0;
        end
        else if (valid_in) begin

            // Step 1: shift in new sample
            shift_reg[0] <= sample_in;
            for (k = 1; k < TAPS; k++)
                shift_reg[k] <= shift_reg[k-1];

            // Step 2: compute filter output
            // y[n] = sum(coeffs_full[k] * shift_reg[k]) for k=0..32
            // Each multiply: 16-bit x 16-bit -> 32-bit, then >>15
            // Note: uses shift_reg values from THIS cycle (before register update)
            // because always_ff non-blocking assignments don't take effect
            // until end of time step — so shift_reg[k] still holds old values
            // during the combinational part of this block
            acc = 32'sd0;
            for (k = 0; k < TAPS; k++) begin
                prod = $signed(shift_reg[k]) * $signed(coeffs_full[k]);
                acc  = acc + (prod >>> 15);
            end

            // Step 3: saturate to 16-bit output
            if      (acc > 32'sd32767)  sample_out <= 16'sd32767;
            else if (acc < -32'sd32768) sample_out <= -16'sd32768;
            else                        sample_out <= acc[15:0];

            valid_out <= 1'b1;
        end
        else begin
            valid_out <= 1'b0;
        end
    end

endmodule