`timescale 1ns/1ps

module tb_threshold_fsm;

    logic        clk;
    logic        rst_n;
    logic        valid_in;
    logic signed [15:0] integrated;
    logic        r_peak;
    logic [15:0] r_peak_idx;

    threshold_fsm dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .valid_in   (valid_in),
        .integrated (integrated),
        .r_peak     (r_peak),
        .r_peak_idx (r_peak_idx)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    localparam N_VECTORS  = 1024;
    localparam TOLERANCE  = 18;    // ±18 samples = ±50ms AHA standard

    logic [15:0] mwi_vec  [0:N_VECTORS-1];

    // Ground truth R-peak indices from Python
    // First 20 detected peaks from mwi output of record 100
    // Generated by running pan_tompkins on filtered signal
    logic [15:0] gt_peaks [0:19];

    integer i;
    integer peak_count;
    integer pass_count;
    integer fail_count;
    integer det_peaks [0:99];   // store up to 100 detected peaks
    integer det_count;
    integer diff;

    initial begin
        $readmemh("D:/Project_3/vectors/mwi_input_hex.txt", mwi_vec);

        // Ground truth peak locations in the MWI signal
        // These are the integrated signal bump peaks — not R-peak indices
        // Approximately every 285-295 samples at 75 bpm
        gt_peaks[0]  = 16'd115;
        gt_peaks[1]  = 16'd401;
        gt_peaks[2]  = 16'd687;
        gt_peaks[3]  = 16'd973;
        gt_peaks[4]  = 16'd259;   // approximate

        rst_n     = 0;
        valid_in  = 0;
        integrated = 0;
        peak_count = 0;
        det_count  = 0;
        pass_count = 0;
        fail_count = 0;

        repeat(5) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        $display("==============================================");
        $display("  THRESHOLD FSM TESTBENCH");
        $display("==============================================");

        for (i = 0; i < N_VECTORS; i++) begin
            @(posedge clk);
            valid_in   = 1;
            integrated = $signed(mwi_vec[i]);

            // Capture detected peaks
            if (r_peak && det_count < 100) begin
                det_peaks[det_count] = r_peak_idx;
                det_count = det_count + 1;
            end
        end

        valid_in = 0;
        repeat(10) @(posedge clk);

        $display("  Detected peaks : %0d", det_count);
        $display("  Expected ~3 peaks in first 1024 samples at 75bpm");
        $display("  Peak indices:");
        for (i = 0; i < det_count; i++)
            $display("    peak[%0d] = %0d", i, det_peaks[i]);

        if (det_count >= 2)
            $display("  RESULT: PEAKS DETECTED - review indices above");
        else
            $display("  RESULT: TOO FEW PEAKS - check threshold");
        $display("==============================================");
        $finish;
    end

endmodule